project_id = "etnlkygkxlnnwxxkkcbi"

[functions.analyze-request-openai]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-proposal]
verify_jwt = true

[functions.geocode-location]
verify_jwt = false

[functions.match-providers]
verify_jwt = false

[functions.notify-providers]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false